[project]
name = "tip-jar"
authors = []
description = ""
telemetry = false
cache_dir = "./.cache"
requirements = []

[repl]
costs_version = 3
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[contracts.tip-jar]
path = "contracts/tip-jar.clar"
clarity_version = 3
epoch = "3.0"

